site_name: PRSice-2
repo_url: https://github.com/choishingwan/PRSice
site_author: Shing Wan CHOI
pages:
    - index.md
    - PRSice:
        - Quick Start: quick_start.md
        - Detailed Guide: step_by_step.md
theme: readthedocs
markdown_extensions:
    - admonition
    - toc:
        permalink: True
    - codehilite:
        linenums: True
